spring:
  application:
    name: order-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  security:
    user:
      name: admin
      password: ${SPRING_SECURITY_PASSWORD}
  cloud:
    config:
      fail-fast: true
    stream:
      defaultBinder: kafka
      kafka:
        binder:
          brokers: kafka.default.svc.cluster.local:9092

jwt:
  secret: ${JWT_SECRET}

server:
  port: 8080

logging:
  level:
    org.springframework.security: WARN
    com.warehouse.order_service.filter: INFO

